// <auto-generated />
using System;
using Core.SqlHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20201222174007_Supertag")]
    partial class Supertag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10");

            modelBuilder.Entity("Core.Objects.Entities.Note", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Core.Objects.Entities.NoteTag", b =>
                {
                    b.Property<int>("NoteKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("NoteKey", "TagKey");

                    b.HasIndex("TagKey");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("Core.Objects.Entities.SuperTag", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SuperTags");
                });

            modelBuilder.Entity("Core.Objects.Entities.Tag", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuperTagKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SuperTagKey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Core.Objects.Entities.NoteTag", b =>
                {
                    b.HasOne("Core.Objects.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Objects.Entities.Tag", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Objects.Entities.Tag", b =>
                {
                    b.HasOne("Core.Objects.Entities.SuperTag", null)
                        .WithMany("Tags")
                        .HasForeignKey("SuperTagKey");
                });
#pragma warning restore 612, 618
        }
    }
}
